<a href="https://colab.research.google.com/github/jose2049/ml-project-colab/blob/main/CampusDataSet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Campus data project
###José Álvarez

##Data preparation

In [52]:
import pandas as pd

In [53]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [54]:
df = pd.read_csv('/content/drive/MyDrive/Machine Learning/CampusWalkDataset_TemplateIDs_final.csv', skiprows=4)

#Inspect the dataset structure

## 1 Errasing empty rows and collums

In [55]:
from re import sub
from numpy._core.defchararray import index
#Eliminating extra columns
df = df.drop(columns=['other_notes', 'Unnamed: 23', 'Unnamed: 24','Unnamed: 25', 'Unnamed: 26'])
#list(df.columns)
# Droping all empty rows. The cahnges take place in the variable df
df.dropna(subset=['date'], inplace=True)
#list(df.index)
print(df.shape)

(135, 22)

#Fixing Teperature Colum
## **Fix points**
### decimal numbers
### mix between numbers and letters

In [56]:
df["temperature_c"] = df["temperature_c"].astype(str).str.replace(r"\D", "", regex=True)
df

,recorder_id,date,location,weather,temperature_c,sound level,foot_traffic,primary_sound_type_urban,other_sound_type_urban,primary_sound_type_nature,...,birds_count,trees_presence,native_or_wild_plant_presence,ornnamental_or_planted_plant_presence,moss_or_lichen_presence,wellbeing_rating,ease_rating,stress_rating,nature_connection_experience_rating,most_notable_nature_element
0,R26_001,22/09/2026,L01 MainEntrance,Partly cloudy,16,Quiet,Low,Human voices,Traffic,Wind,...,1.0,Many,Some,Some,Some,Positive wellbeing,Neutral,Stressful,Less connected,Plants and trees
1,R26_001,22/09/2026,L02 LibraryGreen,Sunny,16,Moderate,Low,Traffic,Human voices,Wind,...,2.0,Many,NaN,Some,NaN,Positive wellbeing,Neutral,Neutral,A little more connected,Sunrays on grass
2,R26_001,22/09/2026,L06 HedgingBehindSportsCentre,Partly cloudy,16,Quiet,Low,Construction,Traffic,Wind,...,20.0,Many,NaN,Many,Some,Positive wellbeing,Easy,Mostly calm,No change,Very quiet
3,R26_001,22/09/2026,L08 AccessRoadNearSportsCentre,Partly cloudy,16,Moderate,Low,Human voices,Human voices,Wind,...,2.0,One or two,Some,NaN,Some,Positive wellbeing,Neutral,Neutral,Much more connected,Harsh wind
4,R26_001,22/09/2026,L06 HedgingBehindSportsCentre,Sunny,16,Moderate,Low,Traffic,Other,Wind,...,0.0,One or two,NaN,Some,NaN,Positive wellbeing,Easy,Mostly calm,Less connected,Crowded area
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,R26_027,23/09/2026,L04 PathFrontiHub,Windy,16,Quiet,Low,Traffic,Human voices,Trees,...,2.0,Many,Some,Some,NaN,Positive wellbeing,Easy,Mostly calm,Much more connected,Plants
134,R26_028,07/10/2026,L10 OtherOffCampus,Windy,10,Quiet,Low,Other,Human voices,Wind,...,0.0,One or two,NaN,NaN,NaN,Neutral,Easy,Mostly calm,Less connected,Trees
135,R26_028,07/10/2026,L10 OtherOffCampus,Windy,10,Moderate,Low,Traffic,Other,Wind,...,1.0,Many,Many,NaN,Some,Positive wellbeing,Easy,Very calm,Much more connected,plants
136,R26_028,07/10/2026,L01 MainEntrance,Partly cloudy,15,Moderate,Moderate,Traffic,Construction,Other birds,...,0.0,Many,Some,NaN,Many,Positive wellbeing,Neutral,Neutral,No change,grass
137,R26_028,07/10/2026,L10 OtherOffCampus,Windy,10,Loud,Moderate,Human voices,Traffic,Wind,...,0.0,NaN,NaN,NaN,Some,Low wellbeing,Neutral,Stressful,Less connected,NaN

#Errasing Non numberic values (NaN)

In [57]:
list(df.columns)

['recorder_id',
 'date',
 'location',
 'weather',
 'temperature_c',
 'sound level',
 'foot_traffic',
 'primary_sound_type_urban',
 'other_sound_type_urban',
 'primary_sound_type_nature',
 'other_sound_type_nature',
 'insects_count',
 'birds_count',
 'trees_presence',
 'native_or_wild_plant_presence',
 'ornnamental_or_planted_plant_presence',
 'moss_or_lichen_presence',
 'wellbeing_rating',
 'ease_rating',
 'stress_rating',
 'nature_connection_experience_rating',
 'most_notable_nature_element']

## I want to try to use a for loop to run through the enteri dataset
## so that it may spot the NaN values and replace them with none

In [58]:
## This for loop runs thorught the entire dataset
## and exchanges the NaN value to none

for index, row in df.iterrows():
    for column in df.columns:
        value = row[column]

        if pd.isna(value):
            df.loc[index, column] = "none"

df

,recorder_id,date,location,weather,temperature_c,sound level,foot_traffic,primary_sound_type_urban,other_sound_type_urban,primary_sound_type_nature,...,birds_count,trees_presence,native_or_wild_plant_presence,ornnamental_or_planted_plant_presence,moss_or_lichen_presence,wellbeing_rating,ease_rating,stress_rating,nature_connection_experience_rating,most_notable_nature_element
0,R26_001,22/09/2026,L01 MainEntrance,Partly cloudy,16,Quiet,Low,Human voices,Traffic,Wind,...,1.0,Many,Some,Some,Some,Positive wellbeing,Neutral,Stressful,Less connected,Plants and trees
1,R26_001,22/09/2026,L02 LibraryGreen,Sunny,16,Moderate,Low,Traffic,Human voices,Wind,...,2.0,Many,none,Some,none,Positive wellbeing,Neutral,Neutral,A little more connected,Sunrays on grass
2,R26_001,22/09/2026,L06 HedgingBehindSportsCentre,Partly cloudy,16,Quiet,Low,Construction,Traffic,Wind,...,20.0,Many,none,Many,Some,Positive wellbeing,Easy,Mostly calm,No change,Very quiet
3,R26_001,22/09/2026,L08 AccessRoadNearSportsCentre,Partly cloudy,16,Moderate,Low,Human voices,Human voices,Wind,...,2.0,One or two,Some,none,Some,Positive wellbeing,Neutral,Neutral,Much more connected,Harsh wind
4,R26_001,22/09/2026,L06 HedgingBehindSportsCentre,Sunny,16,Moderate,Low,Traffic,Other,Wind,...,0.0,One or two,none,Some,none,Positive wellbeing,Easy,Mostly calm,Less connected,Crowded area
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,R26_027,23/09/2026,L04 PathFrontiHub,Windy,16,Quiet,Low,Traffic,Human voices,Trees,...,2.0,Many,Some,Some,none,Positive wellbeing,Easy,Mostly calm,Much more connected,Plants
134,R26_028,07/10/2026,L10 OtherOffCampus,Windy,10,Quiet,Low,Other,Human voices,Wind,...,0.0,One or two,none,none,none,Neutral,Easy,Mostly calm,Less connected,Trees
135,R26_028,07/10/2026,L10 OtherOffCampus,Windy,10,Moderate,Low,Traffic,Other,Wind,...,1.0,Many,Many,none,Some,Positive wellbeing,Easy,Very calm,Much more connected,plants
136,R26_028,07/10/2026,L01 MainEntrance,Partly cloudy,15,Moderate,Moderate,Traffic,Construction,Other birds,...,0.0,Many,Some,none,Many,Positive wellbeing,Neutral,Neutral,No change,grass
137,R26_028,07/10/2026,L10 OtherOffCampus,Windy,10,Loud,Moderate,Human voices,Traffic,Wind,...,0.0,none,none,none,Some,Low wellbeing,Neutral,Stressful,Less connected,none

In [59]:
print(df.head(10).to_string(index=False))
print(df.shape)

recorder_id       date                       location       weather temperature_c sound level foot_traffic primary_sound_type_urban other_sound_type_urban primary_sound_type_nature other_sound_type_nature  insects_count  birds_count trees_presence native_or_wild_plant_presence ornnamental_or_planted_plant_presence moss_or_lichen_presence        wellbeing_rating ease_rating stress_rating nature_connection_experience_rating most_notable_nature_element
    R26_001 22/09/2026               L01 MainEntrance Partly cloudy            16       Quiet          Low             Human voices                Traffic                      Wind                   Trees            0.0          1.0           Many                         Some                                  Some                     Some      Positive wellbeing     Neutral     Stressful                      Less connected            Plants and trees
    R26_001 22/09/2026               L02 LibraryGreen         Sunny            16    Moderate          Low                  Traffic           Human voices                      Wind                   Trees            0.0          2.0           Many                          none                                 Some                     none      Positive wellbeing     Neutral       Neutral             A little more connected            Sunrays on grass
    R26_001 22/09/2026  L06 HedgingBehindSportsCentre Partly cloudy            16       Quiet          Low             Construction                Traffic                      Wind             Other birds           10.0         20.0           Many                          none                                  Many                    Some      Positive wellbeing        Easy   Mostly calm                           No change                  Very quiet
    R26_001 22/09/2026 L08 AccessRoadNearSportsCentre Partly cloudy            16    Moderate          Low             Human voices           Human voices                      Wind             Other birds            0.0          2.0     One or two                         Some                                   none                    Some      Positive wellbeing     Neutral       Neutral                 Much more connected                 Harsh wind
    R26_001 22/09/2026  L06 HedgingBehindSportsCentre         Sunny            16    Moderate          Low                  Traffic                  Other                      Wind                   Trees            0.0          0.0     One or two                          none                                 Some                     none      Positive wellbeing        Easy   Mostly calm                      Less connected               Crowded area
    R26_002 22/09/2026               L01 MainEntrance         Sunny            17    Moderate          Low                  Traffic           Human voices               Other birds                 Insects            2.0          4.0           Many                         Some                                  Some                     Many      Positive wellbeing        Easy   Mostly calm             A little more connected                       trees
    R26_002 22/09/2026              L04 PathFrontiHub         Windy            17    Moderate          Low                  Traffic                  Other                      Wind                 Insects            2.0          2.0           Many                         Some                                   Many                    Some                 Neutral     Neutral     Very calm                           No change            plants and trees
    R26_002 22/09/2026     L05 GreenFrontSportsCentre         Sunny            19    Moderate          Low                  Traffic      Service machinery                      Wind                   Other            7.0          0.0           Many                          Many                                  Many                    Many      Positive wellbeing    Vey easy   Mostly calm                 Much more connected                 wild plants
    R26_002 22/09/2026  L06 HedgingBehindSportsCentre        Cloudy            16       Quiet          Low                  Traffic           Human voices                      Wind                   Trees            3.0          1.0           Many                          Many                                  Many                    Some                 Neutral     Neutral     Very calm                      Less connected               shaded  area
    R26_002 22/09/2026    L07 CarParkNearSportsCentre         Sunny            18       Quiet          Low        Service machinery                Traffic               Other birds                   Trees            6.0          2.0           Many                          Many                                  Many                    Some Very positive wellbeing    Vey easy     Very calm                 Much more connected                     insects
(135, 22)

## I want to apply K-means clustering
## What do I need to apply this?